name: Publish release
on:
    push:
        tags:
            - "*"
jobs:
    publish:
        name: Publish release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Publish release
              uses: ghalactic/github-release-from-tag@v5
              if: github.event_name == 'push' && github.ref_type == 'tag'
